<?php

declare(strict_types=1);

namespace Kwork\Traits;

use GuzzleHttp\Promise\PromiseInterface;

/**
 * Auto-generated async OpenAPI endpoint wrappers.
 *
 * @generated by tools/generate_async_openapi_trait.py
 */
trait AsyncOpenAPIMethodsTrait
{
    /**
     * Принятие предложенных опции в треке покупателем
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function acceptExtrasAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'acceptExtras', $useToken, $params);
    }

    /**
     * Принятие встречного предложения этапов
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function acceptStageSuggestionAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'acceptStageSuggestion', $useToken, $params);
    }

    /**
     * Данные авторизованного пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function actorAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('actor', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Изменение списка любимых категорий пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function addFavoriteCategoriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'addFavoriteCategories', $useToken, $params);
    }

    /**
     * Проверка кода активации для добавления нового номера телефона на замену старому
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function addNewPhoneNumberAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'addNewPhoneNumber', $useToken, $params);
    }

    /**
     * Запрос кода для добавления номера телефона
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function addPhoneNumberAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'addPhoneNumber', $useToken, $params);
    }

    /**
     * Создание и резервирование этапа в заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function addStageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'addStage', $useToken, $params);
    }

    /**
     * Разрешить/не разрешить переписку с пользователем
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function allowInboxRequestAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'allowInboxRequest', $useToken, $params);
    }

    /**
     * Устанавливает/снимает флаг разрешения отправки пуша в мобильное приложение
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function allowMobilePushAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'allowMobilePush', $useToken, $params);
    }

    /**
     * Разрешить продавцу публикацию работы в портфолио
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function allowOrderPortfolioUploadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'allowOrderPortfolioUpload', $useToken, $params);
    }

    /**
     * Устанавливать / снимать флаг разрешения воспроизведения звука при отображении пуша в мобильном приложении.
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function allowPushNotificationsSoundAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'allowPushNotificationsSound', $useToken, $params);
    }

    /**
     * Аутентификация пользователя через Apple
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function appleSignInAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('appleSignIn', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Установить выбранные фильтры продавца на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function applyFiltersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'applyFilters', $useToken, $params);
    }

    /**
     * Принятие заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function approveOrderAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'approveOrder', $useToken, $params);
    }

    /**
     * Принятие этапов заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function approveOrderStageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'approveOrderStage', $useToken, $params);
    }

    /**
     * Отправить диалог в архив
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function archiveDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'archiveDialog', $useToken, $params);
    }

    /**
     * Заблокировать диалог
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function blockDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'blockDialog', $useToken, $params);
    }

    /**
     * Список заблокированных для диалога юзеров
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function blockedDialogListAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'blockedDialogList', $useToken, $params);
    }

    /**
     * Удалить неоплаченный заказ
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function cancelOrderAwaitingPaymentAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'cancelOrderAwaitingPayment', $useToken, $params);
    }

    /**
     * Покупатель отменяет заказ
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function cancelOrderByPayerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('cancelOrderByPayer', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Продавец отменяет заказ
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function cancelOrderByWorkerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('cancelOrderByWorker', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Получение списка подкатегорий
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function catalogCategoriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'catalogCategories', $useToken, $params);
    }

    /**
     * Список фильтров из текущего раздела каталога
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function catalogFiltersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'catalogFilters', $useToken, $params);
    }

    /**
     * Получение основной информации по главной странице каталога
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function catalogMainAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'catalogMain', $useToken, $params);
    }

    /**
     * Получение основной информации по главной странице нового каталога
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function catalogMainv2Async(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'catalogMainv2', $useToken, $params);
    }

    /**
     * Рубрики меню
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function catalogRubricsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'catalogRubrics', $useToken, $params);
    }

    /**
     * Список категорий
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function categoriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'categories', $useToken, $params);
    }

    /**
     * Получить данные о заданной категории
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function categoryAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'category', $useToken, $params);
    }

    /**
     * Получить дерево всех атрибутов для заданной категории
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function categoryAttributesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'categoryAttributes', $useToken, $params);
    }

    /**
     * Запрос изменения пароля пользователя, с отправкой посылка кода подтверждения на почту
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function changePasswordAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('changePassword', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Сменить дочернюю роль покупателя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function changePayerSubRoleAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'changePayerSubRole', $useToken, $params);
    }

    /**
     * Запрос изменения логина пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function changeUsernameAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('changeUsername', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Запрос проверки занятости логина
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function checkLoginAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('checkLogin', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Проверить дублирование идентификатора устройства UAD
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function checkUadDuplicateAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'checkUadDuplicate', $useToken, $params);
    }

    /**
     * Получение списка городов страны
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function citiesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'cities', $useToken, $params);
    }

    /**
     * Сбросить выбранных фильтров продавца на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function clearFiltersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'clearFilters', $useToken, $params);
    }

    /**
     * Покупатель соглашается на обоюдную отмену заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function confirmCancelOrderRequestByPayerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'confirmCancelOrderRequestByPayer', $useToken, $params);
    }

    /**
     * Продавец соглашается на обоюдную отмену заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function confirmCancelOrderRequestByWorkerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'confirmCancelOrderRequestByWorker', $useToken, $params);
    }

    /**
     * Получение списка стран
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function countriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'countries', $useToken, $params);
    }

    /**
     * Создать ответ на отзыв
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function createAnswerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('createAnswer', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Создание жалобы на кворк
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function createKworkComplainAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('createKworkComplain', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Добавить портфолио
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function createPortfolioAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'createPortfolio', $useToken, $params);
    }

    /**
     * Создать отзыв
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function createReviewAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('createReview', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Добавление этапа в заказ
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function createStageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'createStage', $useToken, $params);
    }

    /**
     * Удаление любимых категорий пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function delFavoriteCategoriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'delFavoriteCategories', $useToken, $params);
    }

    /**
     * Удаление своего аккаунта
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteAccountAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteAccount', $useToken, $params);
    }

    /**
     * Покупатель удалил свой запрос на обоюдную отмену заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteCancelOrderRequestByPayerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteCancelOrderRequestByPayer', $useToken, $params);
    }

    /**
     * Продавец удалил свой запрос на обоюдную отмену заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteCancelOrderRequestByWorkerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteCancelOrderRequestByWorker', $useToken, $params);
    }

    /**
     * Удаление обложки пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteCoverAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteCover', $useToken, $params);
    }

    /**
     * Удаление своего кворка
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteKworkAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteKwork', $useToken, $params);
    }

    /**
     * Удаляет предложение к запросу на услугу на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteOfferAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteOffer', $useToken, $params);
    }

    /**
     * Удалить заметку о заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteOrderNoteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteOrderNote', $useToken, $params);
    }

    /**
     * Удаление портфолио
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deletePortfolioAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deletePortfolio', $useToken, $params);
    }

    /**
     * Удаление отзыва
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteReviewAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteReview', $useToken, $params);
    }

    /**
     * Удаление этапа из заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteStageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteStage', $useToken, $params);
    }

    /**
     * Удалить заметку о пользователе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteUserNoteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteUserNote', $useToken, $params);
    }

    /**
     * Удаляет запрос на услугу на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function deleteWantAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'deleteWant', $useToken, $params);
    }

    /**
     * Список диалогов
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function dialogsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'dialogs', $useToken, $params);
    }

    /**
     * Редактировать отзыв
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function editAnswerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('editAnswer', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Редактировать портфолио
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function editPortfolioAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'editPortfolio', $useToken, $params);
    }

    /**
     * Редактировать отзыв
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function editReviewAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('editReview', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Редактирование этапов в заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function editStageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'editStage', $useToken, $params);
    }

    /**
     * Запрос отправки письма подтверждения email
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function emailVerificationLetterAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'emailVerificationLetter', $useToken, $params);
    }

    /**
     * Ключевая информации по бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function exchangeInfoAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'exchangeInfo', $useToken, $params);
    }

    /**
     * Получение списка любимых рубрик пользователя.
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function favoriteCategoriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'favoriteCategories', $useToken, $params);
    }

    /**
     * Список избранных кворков
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function favoriteKworksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'favoriteKworks', $useToken, $params);
    }

    /**
     * Пометка сообщений FCM прочитанными в МП
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function fcmNotificationsReadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'fcmNotificationsRead', $useToken, $params);
    }

    /**
     * Пометка сообщений FCM полученными в МП
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function fcmNotificationsReceivedAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'fcmNotificationsReceived', $useToken, $params);
    }

    /**
     * Регистрация токена Firebase Cloud Messaging
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function fcmTokenRequestFailedAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'fcmTokenRequestFailed', $useToken, $params);
    }

    /**
     * Удаление загруженного файла
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function fileDeleteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'fileDelete', $useToken, $params);
    }

    /**
     * Загрузка файла из FILES["upload_files"]
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function fileUploadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('fileUpload', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Информация о текущем залогиненном пользователе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getActorInfoAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('getActorInfo', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Получить список причин перевода в арбитраж
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getArbitrationReasonsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getArbitrationReasons', $useToken, $params);
    }

    /**
     * Информация о доступных функциях
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getAvailableFeaturesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getAvailableFeatures', $useToken, $params);
    }

    /**
     * Плучение информации для бейджей о количестве важных уведомлений
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getBadgesInfoAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('getBadgesInfo', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Получить ссылку для Yescrow платежа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getBillRefillUrlAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getBillRefillUrl', $useToken, $params);
    }

    /**
     * Требуется ли показать капчу при запросе сброса пароля
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getCaptchaStatusAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getCaptchaStatus', $useToken, $params);
    }

    /**
     * Получить идентификатор socket-канала текущего пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getChannelAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getChannel', $useToken, $params);
    }

    /**
     * Получение деталей о компании по ИНН
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getCompanyDetailsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getCompanyDetails', $useToken, $params);
    }

    /**
     * Получение списка жалоб
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getComplainCategoriesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getComplainCategories', $useToken, $params);
    }

    /**
     * Получение куки для авторизованных по токену
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getCookieAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getCookie', $useToken, $params);
    }

    /**
     * Возвращает список текущих версий мобильных приложений
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getCurrentVersionsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getCurrentVersions', $useToken, $params);
    }

    /**
     * Получить спиок цен для кастомных опций и добавляемого срока
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getCustomOptionsPresetsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getCustomOptionsPresets', $useToken, $params);
    }

    /**
     * Получить диалог по идентификатору собеседника
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getDialog', $useToken, $params);
    }

    /**
     * Получить опции, доступные для добавления в заказ
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getExtrasAvailableForOrderAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getExtrasAvailableForOrder', $useToken, $params);
    }

    /**
     * Список вопросов для опроса о мошенниках (код 116)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getFishingTutorialQuestionsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getFishingTutorialQuestions', $useToken, $params);
    }

    /**
     * Получить список скрытых пользователем кворков
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getHiddenKworksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getHiddenKworks', $useToken, $params);
    }

    /**
     * Получение In-app уведомлений
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getInAppNotificationAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getInAppNotification', $useToken, $params);
    }

    /**
     * Список сообщений (c треками) в диалоге
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getInboxTracksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getInboxTracks', $useToken, $params);
    }

    /**
     * Получение FAQ по кворку
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkAnswersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkAnswers', $useToken, $params);
    }

    /**
     * Получение данных о кворке
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkDetailsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkDetails', $useToken, $params);
    }

    /**
     * Получение данных о кворке
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkDetailsExtraAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkDetailsExtra', $useToken, $params);
    }

    /**
     * Получить данные по ссылкам кворка
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkLinksTableAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkLinksTable', $useToken, $params);
    }

    /**
     * Получить данные по ссылкам кворка
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkLinksTablev2Async(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkLinksTablev2', $useToken, $params);
    }

    /**
     * Получить работы портфолио для кворка
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkPortfoliosAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkPortfolios', $useToken, $params);
    }

    /**
     * Получить отзывы для кворка
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getKworkReviewsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getKworkReviews', $useToken, $params);
    }

    /**
     * Получить список причин отмены заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getOrderCancellationReasonsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getOrderCancellationReasons', $useToken, $params);
    }

    /**
     * Получение детальной информации о заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getOrderDetailsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getOrderDetails', $useToken, $params);
    }

    /**
     * Получить список файлов заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getOrderFilesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getOrderFiles', $useToken, $params);
    }

    /**
     * Обновление блоков кеша шапки заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getOrderHeaderAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getOrderHeader', $useToken, $params);
    }

    /**
     * Предоставленные данные по заказу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getOrderProvidedDataAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getOrderProvidedData', $useToken, $params);
    }

    /**
     * Получение дополнительных опций, которые уже добавлены в заказ
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getOrderedExtrasAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getOrderedExtras', $useToken, $params);
    }

    /**
     * Получение ссылки на страницу покупателя с открытой модалкой регистрации Компании
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getPayerCompanyModalUrlAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('get', 'getPayerCompanyModalUrl', $useToken, $params);
    }

    /**
     * Получение способов оплаты и информации о сервисном сборе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getPaymentMethodsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getPaymentMethods', $useToken, $params);
    }

    /**
     * Получения данных для экрана "Безопасность"
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getSecurityUserDataAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getSecurityUserData', $useToken, $params);
    }

    /**
     * Данные о динамике подписчиков на канале
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getSubscribersStatisticsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getSubscribersStatistics', $useToken, $params);
    }

    /**
     * Возвращает информацию о треках заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getTracksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getTracks', $useToken, $params);
    }

    /**
     * Получение информации о пользователе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getUserInfoAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getUserInfo', $useToken, $params);
    }

    /**
     * Возвращает информацию по последнему выполненному заказу между пользователем и собеседником, в котором было хотя бы одно сообщение
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getUsersLastOrderInfoAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getUsersLastOrderInfo', $useToken, $params);
    }

    /**
     * Получить статус конвертации голосового сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getVoiceMessageConvertStatusAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getVoiceMessageConvertStatus', $useToken, $params);
    }

    /**
     * Получить транскрипцию голосового сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getVoiceMessageTranscriptionAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getVoiceMessageTranscription', $useToken, $params);
    }

    /**
     * Возвращает количество проектов по заданным фильтрам
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getWantsCountAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getWantsCount', $useToken, $params);
    }

    /**
     * Получить токен входа в веб версию
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function getWebAuthTokenAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'getWebAuthToken', $useToken, $params);
    }

    /**
     * Скрыть/удалить диалог
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function hideDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'hideDialog', $useToken, $params);
    }

    /**
     * Скрыть уведомление об успешной регистрации СЗ/ИП
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function hideSelfEmployedNotificationAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'hideSelfEmployedNotification', $useToken, $params);
    }

    /**
     * Отправка на бэк факта показа попапа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function hideVoiceMessageSettingsPopupAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'hideVoiceMessageSettingsPopup', $useToken, $params);
    }

    /**
     * Пожаловаться на сообщение пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxComplainMessageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('inboxComplainMessage', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Создание нового сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxCreateAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('inboxCreate', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Отмена индивидуального запроса
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxCustomRequestDeclineAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxCustomRequestDecline', $useToken, $params);
    }

    /**
     * Удаление сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxDeleteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxDelete', $useToken, $params);
    }

    /**
     * Редактирование сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxEditAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('inboxEdit', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Пересылка сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxForwardAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxForward', $useToken, $params);
    }

    /**
     * Получить сообщение Inbox по id
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxMessageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxMessage', $useToken, $params);
    }

    /**
     * Отмена предложенного кворка в личке покупателем
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxPayerDeclineAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxPayerDecline', $useToken, $params);
    }

    /**
     * Пометить прочитанным сообщения или диалог
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxReadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxRead', $useToken, $params);
    }

    /**
     * Получить сообщение Inbox/Track по conversationId
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxTrackMessageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxTrackMessage', $useToken, $params);
    }

    /**
     * Отмена предложенного кворка в личке продавцом
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxWorkerDeclineAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxWorkerDecline', $useToken, $params);
    }

    /**
     * Список сообщений в диалоге
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function inboxesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'inboxes', $useToken, $params);
    }

    /**
     * Разрешен ли диалог с пользователем
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function isDialogAllowAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'isDialogAllow', $useToken, $params);
    }

    /**
     * Список кворков для категории
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function kworksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'kworks', $useToken, $params);
    }

    /**
     * Получение вкладок пользователя с категориями кворков
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function kworksCategoriesListAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'kworksCategoriesList', $useToken, $params);
    }

    /**
     * Получение статусов (вкладок) кворков, и первую страницу самих кворков для каждого статуса
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function kworksStatusListAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'kworksStatusList', $useToken, $params);
    }

    /**
     * Выход пользователя: удаление указанного пуш токена, удаление токена авторизации, закрытие текущей сессии
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function logoutAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'logout', $useToken, $params);
    }

    /**
     * Пометить переписку пользователя прочитанной
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function markInboxTracksAsReadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'markInboxTracksAsRead', $useToken, $params);
    }

    /**
     * Добавление кворка в избранные или удаление из избранных
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function markKworkAsFavoriteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'markKworkAsFavorite', $useToken, $params);
    }

    /**
     * Скрытие\отображение кворка
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function markKworkAsHiddenAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'markKworkAsHidden', $useToken, $params);
    }

    /**
     * Отмечает кворк участвующим в акции Черная пятница
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function markKworksBlackFridayAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'markKworksBlackFriday', $useToken, $params);
    }

    /**
     * Отправить флаг "Пользователь прослушал голосовое сообщение"
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function markVoiceMessageHeardAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'markVoiceMessageHeard', $useToken, $params);
    }

    /**
     * Получить миниатюру к файлу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function miniatureAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'miniature', $useToken, $params);
    }

    /**
     * Возвращает список запросов на услугу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function myWantsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'myWants', $useToken, $params);
    }

    /**
     * Список уведомлений пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function notificationsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'notifications', $useToken, $params);
    }

    /**
     * Получение непрочитанных Push-событий из очереди
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function notificationsFetchAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'notificationsFetch', $useToken, $params);
    }

    /**
     * Пометка сквозных Push-событий прочтенными
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function notificationsReceivedAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'notificationsReceived', $useToken, $params);
    }

    /**
     * Получает данные предложения к запросу на услугу на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function offerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'offer', $useToken, $params);
    }

    /**
     * Добавить предложение опций к заказу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function offerOrderOptionsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'offerOrderOptions', $useToken, $params);
    }

    /**
     * Предложения пользователя на запросы услуг на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function offersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'offers', $useToken, $params);
    }

    /**
     * Установить статус offline
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function offlineAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'offline', $useToken, $params);
    }

    /**
     * Информация о заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function orderAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'order', $useToken, $params);
    }

    /**
     * Создать заказ по кворку.
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function orderKworkAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'orderKwork', $useToken, $params);
    }

    /**
     * Зарезервировать этапы
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function orderStageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'orderStage', $useToken, $params);
    }

    /**
     * Список активных заказов между текущим пользователем и указанным
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function ordersBetweenAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'ordersBetween', $useToken, $params);
    }

    /**
     * Останавливает кворк
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function pauseKworkAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'pauseKwork', $useToken, $params);
    }

    /**
     * Оплата заказа в статусе "Ожидает оплаты"
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payOrderAwaitingPaymentAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payOrderAwaitingPayment', $useToken, $params);
    }

    /**
     * Добавление опции в заказ покупателем
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payerBuyExtrasAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payerBuyExtras', $useToken, $params);
    }

    /**
     * Покупатель отклоняет предложенные опции
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payerDeclineExtrasAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payerDeclineExtras', $useToken, $params);
    }

    /**
     * Покупатель отклоняет запрос на удаление опции из заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payerDeclinesExtraRemovalRequestAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payerDeclinesExtraRemovalRequest', $useToken, $params);
    }

    /**
     * Удалить опцию из заказа, для покупателя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payerExtraDeleteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payerExtraDelete', $useToken, $params);
    }

    /**
     * Список заказов покупателя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payerOrdersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payerOrders', $useToken, $params);
    }

    /**
     * Апгрейд пакета покупателем
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function payerUpgradePackageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'payerUpgradePackage', $useToken, $params);
    }

    /**
     * Получение категорий работ, и первой страницы самих работ для каждой категории
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function portfolioCategoriesListAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'portfolioCategoriesList', $useToken, $params);
    }

    /**
     * Получить портфолио пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function portfolioListAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'portfolioList', $useToken, $params);
    }

    /**
     * Получить массив количества отзывов по атрибуту
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function positiveReviewsCountAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'positiveReviewsCount', $useToken, $params);
    }

    /**
     * Вывод политики конфиденциальности
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function privacyAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'privacy', $useToken, $params);
    }

    /**
     * Возвращает проект по идентификатору
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function projectAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'project', $useToken, $params);
    }

    /**
     * Возвращает список проектов по заданным фильтрам
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function projectsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'projects', $useToken, $params);
    }

    /**
     * Запись лога показа in-app уведомления
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function pushInAppNotificationLogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'pushInAppNotificationLog', $useToken, $params);
    }

    /**
     * Выставление оценки за арбитраж
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function rateArbitrationAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'rateArbitration', $useToken, $params);
    }

    /**
     * Получить ссылку для пополнения баланса в профиле и для создания заказа.
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function rechargeBalanceAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'rechargeBalance', $useToken, $params);
    }

    /**
     * Регистрация токена Firebase Cloud Messaging
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function registerCloudTokenAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'registerCloudToken', $useToken, $params);
    }

    /**
     * Покупатель не согласился на обоюдную отмену заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function rejectCancelOrderRequestByPayerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'rejectCancelOrderRequestByPayer', $useToken, $params);
    }

    /**
     * Продавец не согласился на обоюдную отмену заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function rejectCancelOrderRequestByWorkerAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'rejectCancelOrderRequestByWorker', $useToken, $params);
    }

    /**
     * Отмена встречного предложения этапов
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function rejectStageSuggestionAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'rejectStageSuggestion', $useToken, $params);
    }

    /**
     * Создать заказ заново
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function repeatOrderAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'repeatOrder', $useToken, $params);
    }

    /**
     * Заменить идентификатор устройства UAD
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function replaceUadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'replaceUad', $useToken, $params);
    }

    /**
     * Обновление версии мобильного приложения пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function reportAppVersionAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'reportAppVersion', $useToken, $params);
    }

    /**
     * Запрос кода для смены номера телефона
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function requestPhoneChangingAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'requestPhoneChanging', $useToken, $params);
    }

    /**
     * Отправка письма для сброса пароля
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function resetPasswordAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('resetPassword', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Вывод политики разрешения споров
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function resolutionAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'resolution', $useToken, $params);
    }

    /**
     * Перезапускает запрос на услугу на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function restartWantAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'restartWant', $useToken, $params);
    }

    /**
     * Создать/редактировать заметку о заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function saveOrderNoteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('saveOrderNote', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Создать/редактировать заметку о пользователе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function saveUserNoteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('saveUserNote', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Поиск кворков
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'search', $useToken, $params);
    }

    /**
     * Поиск диалогов
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchDialogsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'searchDialogs', $useToken, $params);
    }

    /**
     * Поиск сообщенений в диалогах пользователей
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchInboxesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'searchInboxes', $useToken, $params);
    }

    /**
     * Получение ключевых слов по частичной фразе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchKworksCatalogQueryAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'searchKworksCatalogQuery', $useToken, $params);
    }

    /**
     * Поиск сообщенений в диалогах пользователей с указанием найденного сниппета
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchMessagesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'searchMessages', $useToken, $params);
    }

    /**
     * Поиск текстовых треков в заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchOrderTracksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'searchOrderTracks', $useToken, $params);
    }

    /**
     * Поиск текстовых треков в заказе
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function searchTracksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'searchTracks', $useToken, $params);
    }

    /**
     * Отправить бонус продавцу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendBonusAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendBonus', $useToken, $params);
    }

    /**
     * Отправка компании на проверку
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendCompanyForVerificationAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendCompanyForVerification', $useToken, $params);
    }

    /**
     * Отправка заказа на проверку
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendOrderForApprovalAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendOrderForApproval', $useToken, $params);
    }

    /**
     * Отправить заказ на арбитраж
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendOrderForArbitrationAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendOrderForArbitration', $useToken, $params);
    }

    /**
     * Отправить заказ на доработку
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendOrderForRevisionAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendOrderForRevision', $useToken, $params);
    }

    /**
     * Отправка ссылки на чек для проверки
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendOrderReceiptLinkForVerificationAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendOrderReceiptLinkForVerification', $useToken, $params);
    }

    /**
     * Отправка информации по заказу продавцу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendOrderRequirementsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendOrderRequirements', $useToken, $params);
    }

    /**
     * Отправить отчет по заказу (не этапному)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendReportAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendReport', $useToken, $params);
    }

    /**
     * Отправить ответ на опрос
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendSelfEmployedSurveyResultAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendSelfEmployedSurveyResult', $useToken, $params);
    }

    /**
     * Отправить флаг "Статус пользователя"
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendUserStatusAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendUserStatus', $useToken, $params);
    }

    /**
     * Отправить код верификации через WhatsApp
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function sendWhatsAppCodeAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'sendWhatsAppCode', $useToken, $params);
    }

    /**
     * Изменение доступности кворков на выходных
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setAvailableAtWeekendsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setAvailableAtWeekends', $useToken, $params);
    }

    /**
     * Пометить диалог избранным
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setDialogStarredAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setDialogStarred', $useToken, $params);
    }

    /**
     * Изменение списка любимых категорий пользователя, объединяет функционал add и delete
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setFavoriteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setFavorite', $useToken, $params);
    }

    /**
     * Установка статуса о прохождении опроса о мошенниках
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setFishingTutorialStatusAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setFishingTutorialStatus', $useToken, $params);
    }

    /**
     * Оценить продавца
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setOrderRatingAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setOrderRating', $useToken, $params);
    }

    /**
     * Сохранение настройки пользователя по доступности его кворков для заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setTakingOrdersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setTakingOrders', $useToken, $params);
    }

    /**
     * Установка типа пользователя (покупатель/продавец)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setUserTypeAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setUserType', $useToken, $params);
    }

    /**
     * Разрешить/запретить принимать голосовые сообщения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setVoiceMessageReceivingAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setVoiceMessageReceiving', $useToken, $params);
    }

    /**
     * Изменение скорости воспроизведения голосовых сообщений
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function setVoiceMessageSpeedAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'setVoiceMessageSpeed', $useToken, $params);
    }

    /**
     * Аутентификация пользователя с выдачей токена
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function signInAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('signIn', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Регистрация пользователя с выдачей токена
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function signUpAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('signUp', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Аутентификация пользователя через социальные сети по коду провайдера
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function socialSignInAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('socialSignIn', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Аутентификация пользователя через токен социальной сети (при нативной авторизации моб. приложений)
Аутентификация + регистрация
(Устаревший метод, вскоре должен быть удален)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function socialSignInByTokenAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('socialSignInByToken', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Аутентификация пользователя через токен социальной сети (при нативной авторизации моб. приложений)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function socialSignInByTokenv2Async(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('socialSignInByTokenv2', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Регистрация через социальные сети с указанием email (привязка социального аккаунта если такой email уже есть)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function socialSignUpAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('socialSignUp', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Регистрация через социальные сети по токену с указанием email (привязка социального аккаунта если такой email уже есть)
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function socialSignUpByTokenAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('socialSignUpByToken', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Активирует(запускает) кворк
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function startKworkAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'startKwork', $useToken, $params);
    }

    /**
     * Останавливает запрос на услугу на бирже
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function stopWantAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'stopWant', $useToken, $params);
    }

    /**
     * Встречное предложение этапов
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function suggestStagesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'suggestStages', $useToken, $params);
    }

    /**
     * Вывод договора-оферты
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function termsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'terms', $useToken, $params);
    }

    /**
     * Вывод правил сайта
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function termsOfServiceAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'termsOfService', $useToken, $params);
    }

    /**
     * Получение списка временных зон
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function timezonesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'timezones', $useToken, $params);
    }

    /**
     * Удаление трека
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function trackDeleteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'trackDelete', $useToken, $params);
    }

    /**
     * Редактирование трека
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function trackEditAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestWithBodyAsync('trackEdit', $useToken, $params['body'] ?? [], $params);
    }

    /**
     * Получить сообщение трека
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function trackMessageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'trackMessage', $useToken, $params);
    }

    /**
     * Пометить указанные треки прочитанными
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function trackReadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'trackRead', $useToken, $params);
    }

    /**
     * Получить массив всех доступных в системе языков для переводов с падежами
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function translationLanguagesAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'translationLanguages', $useToken, $params);
    }

    /**
     * Отправить флаг "Юзер печатает"
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function typingAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'typing', $useToken, $params);
    }

    /**
     * Вернуть диалог из архива
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function unarchiveDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'unarchiveDialog', $useToken, $params);
    }

    /**
     * Разблокировать диалог
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function unblockDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'unblockDialog', $useToken, $params);
    }

    /**
     * Пометить диалог с заданным пользователем непрочитанным
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function unreadDialogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'unreadDialog', $useToken, $params);
    }

    /**
     * Смена аватара пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function updateAvatarAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('updateAvatar', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Обновление черновика
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function updateChatDraftMessageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'updateChatDraftMessage', $useToken, $params);
    }

    /**
     * Обновление черновика
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function updateOrderDraftMessageAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'updateOrderDraftMessage', $useToken, $params);
    }

    /**
     * Редактирование настроек пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function updateSettingsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('updateSettings', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Обновить прогресс по задаче
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function updateStageProgressAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'updateStageProgress', $useToken, $params);
    }

    /**
     * Загрузка обложки пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function uploadCoverAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('uploadCover', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Загрузка лога мобильного приложения
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function uploadLogAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('uploadLog', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Загрузка файла из FILES["file"]
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function uploadPortfolioFileAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('uploadPortfolioFile', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Получение загруженного файла
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function uploadedFileAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'uploadedFile', $useToken, $params);
    }

    /**
     * Данные пользователя по идентификатору
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function userAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'user', $useToken, $params);
    }

    /**
     * Получение данных пользователя по username
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function userByUsernameAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'userByUsername', $useToken, $params);
    }

    /**
     * Список кворков пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function userKworksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'userKworks', $useToken, $params);
    }

    /**
     * Список отзывов для пользователя
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function userReviewsAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'userReviews', $useToken, $params);
    }

    /**
     * Поиск пользователей
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function userSearchAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'userSearch', $useToken, $params);
    }

    /**
     * Проверка кода активации номера телефона
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function verifyPhoneActivationCodeAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'verifyPhoneActivationCode', $useToken, $params);
    }

    /**
     * Проверка кода удаления аккаунта
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function verifySmsCodeForAccountDeletingAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'verifySmsCodeForAccountDeleting', $useToken, $params);
    }

    /**
     * Список просмотренных кворков
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function viewedCatalogKworksAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'viewedCatalogKworks', $useToken, $params);
    }

    /**
     * Загрузка файла из FILES["upload_files"]
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function voiceUploadAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestMultipartAsync('voiceUpload', $useToken, $params['fields'] ?? [], $params);
    }

    /**
     * Возвращает данные по запросу на услугу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function wantAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'want', $useToken, $params);
    }

    /**
     * Список запросов на услугу на бирже, сгруппированных по альтернативному статусу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function wantsStatusListAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'wantsStatusList', $useToken, $params);
    }

    /**
     * Продавец подтверждает запрос на удаление опции
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function workerConfirmsExtraRemovalRequestAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'workerConfirmsExtraRemovalRequest', $useToken, $params);
    }

    /**
     * Продавец отклоняет предложенные опции
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function workerDeclineExtrasAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'workerDeclineExtras', $useToken, $params);
    }

    /**
     * Продавец отклоняет запрос на удаление опции из заказа
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function workerDeclinesExtraRemovalRequestAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'workerDeclinesExtraRemovalRequest', $useToken, $params);
    }

    /**
     * Удалить опцию из заказа, для продавца
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function workerExtraDeleteAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'workerExtraDelete', $useToken, $params);
    }

    /**
     * Продавец взял заказ в работу
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function workerInprogressAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'workerInprogress', $useToken, $params);
    }

    /**
     * Список заказов пользователя, которые он должен выполнить
     * @param array<string, mixed> $params
     * @return PromiseInterface<array<string, mixed>>
     */
    public function workerOrdersAsync(bool $useToken = true, array $params = []): PromiseInterface
    {
        return $this->requestAsync('post', 'workerOrders', $useToken, $params);
    }

}
