#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Regenerate src/Traits/OpenAPIMethodsTrait.php from docs/openapi.json.
 *
 * Usage: php tools/generate_openapi_trait.php
 */

$root = dirname(__DIR__);
$specPath = $root . '/docs/openapi.json';
$outPath = $root . '/src/Traits/OpenAPIMethodsTrait.php';

if (!is_readable($specPath)) {
    fwrite(STDERR, "Missing {$specPath}\n");
    exit(1);
}

/** @var array<string, mixed> $spec */
$spec = json_decode(file_get_contents($specPath), true, flags: JSON_THROW_ON_ERROR);
$paths = $spec['paths'] ?? [];

$methods = [];

foreach ($paths as $path => $operations) {
    if (!is_array($operations)) {
        continue;
    }

    foreach ($operations as $httpMethod => $operation) {
        if (!is_array($operation) || !in_array(strtolower((string) $httpMethod), ['get', 'post'], true)) {
            continue;
        }

        $endpoint = ltrim($path, '/');
        $phpName = pathToCamel($endpoint);
        $useToken = requiresToken($operation);
        $hasBody = isset($operation['requestBody']);
        $isMultipart = $hasBody && hasMultipart($operation);

        $methods[$phpName] = [
            'endpoint' => $endpoint,
            'http' => strtolower((string) $httpMethod),
            'useToken' => $useToken,
            'hasBody' => $hasBody && !$isMultipart,
            'isMultipart' => $isMultipart,
            'summary' => trim((string) ($operation['summary'] ?? '')),
        ];
    }
}

ksort($methods);

$lines = [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    'namespace Kwork\\Traits;',
    '',
    '/**',
    ' * Auto-generated OpenAPI endpoint wrappers.',
    ' *',
    ' * @generated by tools/generate_openapi_trait.php',
    ' */',
    'trait OpenAPIMethodsTrait',
    '{',
];

foreach ($methods as $name => $meta) {
    $doc = $meta['summary'] !== '' ? "     * {$meta['summary']}\n" : '';
    $defaultToken = $meta['useToken'] ? 'true' : 'false';

    $lines[] = '    /**';
    if ($doc !== '') {
        $lines[] = rtrim($doc);
    }
    $lines[] = '     * @param array<string, mixed> $params';
    $lines[] = '     * @return array<string, mixed>';
    $lines[] = '     */';
    $lines[] = "    public function {$name}(bool \$useToken = {$defaultToken}, array \$params = []): array";
    $lines[] = '    {';

    if ($meta['isMultipart']) {
        $lines[] = "        return \$this->requestMultipart('{$meta['endpoint']}', \$useToken, \$params['fields'] ?? [], \$params);";
    } elseif ($meta['hasBody']) {
        $lines[] = "        return \$this->requestWithBody('{$meta['endpoint']}', \$useToken, \$params['body'] ?? [], \$params);";
    } else {
        $lines[] = "        return \$this->request('{$meta['http']}', '{$meta['endpoint']}', \$useToken, \$params);";
    }

    $lines[] = '    }';
    $lines[] = '';
}

$lines[] = '}';
$lines[] = '';

file_put_contents($outPath, implode("\n", $lines));
fwrite(STDOUT, 'Generated ' . count($methods) . " methods -> {$outPath}\n");

function pathToCamel(string $path): string
{
    $parts = preg_split('/[\/_-]+/', $path) ?: [];
    $first = array_shift($parts) ?: $path;

    return $first . implode('', array_map(static fn (string $p): string => ucfirst($p), $parts));
}

/** @param array<string, mixed> $operation */
function requiresToken(array $operation): bool
{
    foreach ($operation['security'] ?? [] as $security) {
        if (is_array($security) && array_key_exists('token', $security)) {
            return true;
        }
    }

    foreach ($operation['tags'] ?? [] as $tag) {
        if (is_string($tag) && str_contains(mb_strtolower($tag), 'token')) {
            return true;
        }
    }

    return false;
}

/** @param array<string, mixed> $operation */
function hasMultipart(array $operation): bool
{
    $content = $operation['requestBody']['content'] ?? null;
    if (!is_array($content)) {
        return false;
    }

    return isset($content['multipart/form-data']);
}
