#!/usr/bin/env python3
"""Generate src/Traits/AsyncOpenAPIMethodsTrait.php from docs/openapi.json."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "docs" / "openapi.json"
OUT = ROOT / "src" / "Traits" / "AsyncOpenAPIMethodsTrait.php"


def path_to_camel(path: str) -> str:
    parts = re.split(r"[/\-_]+", path.strip("/"))
    if not parts:
        return path
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def requires_token(operation: dict) -> bool:
    for security in operation.get("security", []):
        if isinstance(security, dict) and "token" in security:
            return True
    for tag in operation.get("tags", []):
        if isinstance(tag, str) and "token" in tag.lower():
            return True
    return False


def has_multipart(operation: dict) -> bool:
    content = operation.get("requestBody", {}).get("content", {})
    return "multipart/form-data" in content


def main() -> None:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    methods = []

    for path, operations in spec.get("paths", {}).items():
        if not isinstance(operations, dict):
            continue
        for http_method, operation in operations.items():
            if http_method.lower() not in ("get", "post") or not isinstance(operation, dict):
                continue
            endpoint = path.lstrip("/")
            methods.append(
                {
                    "name": path_to_camel(endpoint),
                    "endpoint": endpoint,
                    "http": http_method.lower(),
                    "use_token": requires_token(operation),
                    "has_body": "requestBody" in operation and not has_multipart(operation),
                    "is_multipart": has_multipart(operation),
                    "summary": (operation.get("summary") or "").strip(),
                }
            )

    methods.sort(key=lambda m: m["name"])

    lines = [
        "<?php",
        "",
        "declare(strict_types=1);",
        "",
        "namespace Kwork\\Traits;",
        "",
        "use GuzzleHttp\\Promise\\PromiseInterface;",
        "",
        "/**",
        " * Auto-generated async OpenAPI endpoint wrappers.",
        " *",
        " * @generated by tools/generate_async_openapi_trait.py",
        " */",
        "trait AsyncOpenAPIMethodsTrait",
        "{",
    ]

    for meta in methods:
        default_token = "true" if meta["use_token"] else "false"
        if meta["summary"]:
            lines.append("    /**")
            lines.append(f"     * {meta['summary']}")
            lines.append("     * @param array<string, mixed> $params")
            lines.append("     * @return PromiseInterface<array<string, mixed>>")
            lines.append("     */")
        else:
            lines.append("    /**")
            lines.append("     * @param array<string, mixed> $params")
            lines.append("     * @return PromiseInterface<array<string, mixed>>")
            lines.append("     */")

        lines.append(
            f"    public function {meta['name']}Async(bool $useToken = {default_token}, array $params = []): PromiseInterface"
        )
        lines.append("    {")

        if meta["is_multipart"]:
            lines.append(
                f"        return $this->requestMultipartAsync('{meta['endpoint']}', $useToken, $params['fields'] ?? [], $params);"
            )
        elif meta["has_body"]:
            lines.append(
                f"        return $this->requestWithBodyAsync('{meta['endpoint']}', $useToken, $params['body'] ?? [], $params);"
            )
        else:
            lines.append(
                f"        return $this->requestAsync('{meta['http']}', '{meta['endpoint']}', $useToken, $params);"
            )

        lines.append("    }")
        lines.append("")

    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(methods)} async methods -> {OUT}")


if __name__ == "__main__":
    main()
